//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public int leave_type_id { get; set; }
        public string leave_type_name { get; set; }
        public string description { get; set; }
    }
}
