//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LeaveRequest
    {
        [Key]
        public int leave_request_Id { get; set; }
        public Nullable<int> fk_user_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string Description { get; set; }
        public string leave_status { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public Nullable<int> fk_approverid_user_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public string AdditionalData { get; internal set; }
        public int SerialNumber { get; internal set; }
    }
}
